#!/usr/bin/env python3
"""Deterministic Schur-complement marginalization and prior replay lab."""
from __future__ import annotations
import json
from pathlib import Path
import cv2,numpy as np
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'out'; OUT.mkdir(exist_ok=True)
def main():
    rng=np.random.default_rng(4); A=rng.normal(size=(8,8)); H=A.T@A+0.5*np.eye(8); b=rng.normal(size=8); keep=np.arange(3,8); rem=np.arange(3); Hrr=H[np.ix_(rem,rem)]; Hrk=H[np.ix_(rem,keep)]; Hkk=H[np.ix_(keep,keep)]; br=b[rem]; bk=b[keep]; prior_H=Hkk-Hrk.T@np.linalg.solve(Hrr,Hrk); prior_b=bk-Hrk.T@np.linalg.solve(Hrr,br); full=np.linalg.solve(H,b); reduced=np.linalg.solve(prior_H,prior_b); replay_err=float(np.max(np.abs(reduced-full[keep]))); sym=float(np.max(np.abs(prior_H-prior_H.T))); eig=np.linalg.eigvalsh(prior_H); checks={k:bool(v) for k,v in {'block_parity':replay_err<1e-10,'symmetric':sym<1e-12,'positive_semidefinite':eig.min()>0,'rank_preserved':np.linalg.matrix_rank(prior_H)==5}.items()}; report={'status':'PASS' if all(checks.values()) else 'FAIL','truth':{'removed_states':3,'retained_states':5},'replay_max_error':replay_err,'symmetry_error':sym,'minimum_eigenvalue':float(eig.min()),'checks':checks,'command':'python3 scripts/marginalization_smoke.py','artifacts':{'report':'out/marginalization_report.json','model':'out/marginalization_model.npz','plot':'out/marginalization_plot.png'}}
    np.savez(OUT/'marginalization_model.npz',H=H,b=b,prior_H=prior_H,prior_b=prior_b,full_solution=full,reduced_solution=reduced)
    canvas=np.full((720,1280,3),246,np.uint8); ink=(45,43,37); teal=(115,140,25); blue=(190,115,34); cv2.putText(canvas,'MARGINALIZATION PARITY',(42,52),cv2.FONT_HERSHEY_SIMPLEX,.78,ink,2,cv2.LINE_AA); cv2.rectangle(canvas,(60,110),(760,635),(215,208,198),1); cv2.putText(canvas,'SCHUR-COMPLEMENT PRIOR',(90,150),cv2.FONT_HERSHEY_SIMPLEX,.55,ink,1,cv2.LINE_AA); vals=[('removed states','3'),('retained states','5'),('replay max error',f'{replay_err:.2e}'),('min eigenvalue',f'{eig.min():.3f}')];
    for i,(a,v) in enumerate(vals): cv2.putText(canvas,a,(100,225+i*78),cv2.FONT_HERSHEY_SIMPLEX,.5,ink,1,cv2.LINE_AA); cv2.putText(canvas,v,(100,260+i*78),cv2.FONT_HERSHEY_SIMPLEX,.66,teal,2,cv2.LINE_AA)
    cv2.rectangle(canvas,(810,110),(1220,635),(215,208,198),1); cv2.putText(canvas,'PRIOR GATES',(850,150),cv2.FONT_HERSHEY_SIMPLEX,.55,ink,1,cv2.LINE_AA); cv2.putText(canvas,'BLOCK PARITY',(850,255),cv2.FONT_HERSHEY_SIMPLEX,.56,ink,1,cv2.LINE_AA); cv2.putText(canvas,'PASS',(850,300),cv2.FONT_HERSHEY_SIMPLEX,.74,teal,2,cv2.LINE_AA); cv2.putText(canvas,'SYMMETRY + RANK',(850,420),cv2.FONT_HERSHEY_SIMPLEX,.56,ink,1,cv2.LINE_AA); cv2.putText(canvas,'PASS',(850,465),cv2.FONT_HERSHEY_SIMPLEX,.74,blue,2,cv2.LINE_AA); cv2.imwrite(str(OUT/'marginalization_plot.png'),canvas); (OUT/'marginalization_report.json').write_text(json.dumps(report,indent=2)+'\n'); print('Marginalization lab:',report['status']); return 0 if report['status']=='PASS' else 1
if __name__=='__main__': raise SystemExit(main())
