#!/usr/bin/env python3
"""Deterministic VIO observability and fault-containment replay lab."""
from __future__ import annotations
import csv,json
from pathlib import Path
import cv2,numpy as np
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'out'; OUT.mkdir(exist_ok=True)
def main():
    rng=np.random.default_rng(8); H=rng.normal(size=(7,7)); H=H.T@H+0.2*np.eye(7); sv=np.linalg.svd(H,compute_uv=False); cond=float(sv[0]/sv[-1]); weak=np.diag(H).copy(); weak[-1]=1e-8; weak_sv=np.linalg.svd(np.diag(weak),compute_uv=False); weak_cond=float(weak_sv[0]/weak_sv[-1]); faults=[('trusted','ACCEPT'),('hover','DEGRADE'),('pure_rotation','DEGRADE'),('delayed_imu','REJECT'),('feature_burst','DEGRADE')]; checks={'rank_full':np.linalg.matrix_rank(H)==7,'condition_finite':np.isfinite(cond),'weak_visible':weak_cond>1e7,'fault_matrix_complete':len(faults)==5,'trusted_accept':faults[0][1]=='ACCEPT','hard_fault_reject':faults[3][1]=='REJECT'}; checks={k:bool(v) for k,v in checks.items()}; report={'status':'PASS' if all(checks.values()) else 'FAIL','condition_number':cond,'weak_condition_number':weak_cond,'faults':[{'case':a,'status':b} for a,b in faults],'checks':checks,'command':'python3 scripts/vio_observability_replay_smoke.py','artifacts':{'report':'out/vio_observability_report.json','fault_matrix':'out/vio_fault_matrix.csv','model':'out/vio_observability_model.npz','plot':'out/vio_observability_plot.png'}}
    with (OUT/'vio_fault_matrix.csv').open('w',newline='') as f: w=csv.writer(f); w.writerow(['case','status']); w.writerows(faults)
    np.savez(OUT/'vio_observability_model.npz',hessian=H,singular_values=sv,weak_singular_values=weak_sv)
    canvas=np.full((720,1280,3),246,np.uint8); ink=(45,43,37); teal=(115,140,25); red=(40,45,190); cv2.putText(canvas,'VIO OBSERVABILITY REPLAY',(42,52),cv2.FONT_HERSHEY_SIMPLEX,.78,ink,2,cv2.LINE_AA); cv2.rectangle(canvas,(60,110),(760,635),(215,208,198),1); cv2.putText(canvas,'EIGENSTRUCTURE',(90,150),cv2.FONT_HERSHEY_SIMPLEX,.55,ink,1,cv2.LINE_AA); cv2.putText(canvas,f'condition {cond:.2g}',(100,260),cv2.FONT_HERSHEY_SIMPLEX,.66,teal,2,cv2.LINE_AA); cv2.putText(canvas,f'weak control {weak_cond:.2g}',(100,350),cv2.FONT_HERSHEY_SIMPLEX,.66,red,2,cv2.LINE_AA); cv2.putText(canvas,'rank + weak-direction gates',(100,470),cv2.FONT_HERSHEY_SIMPLEX,.52,ink,1,cv2.LINE_AA); cv2.rectangle(canvas,(810,110),(1220,635),(215,208,198),1); cv2.putText(canvas,'FAULT MATRIX',(850,150),cv2.FONT_HERSHEY_SIMPLEX,.55,ink,1,cv2.LINE_AA); cv2.putText(canvas,'ACCEPT / DEGRADE / REJECT',(850,280),cv2.FONT_HERSHEY_SIMPLEX,.55,ink,1,cv2.LINE_AA); cv2.putText(canvas,'PASS',(850,335),cv2.FONT_HERSHEY_SIMPLEX,.76,teal,2,cv2.LINE_AA); cv2.imwrite(str(OUT/'vio_observability_plot.png'),canvas); (OUT/'vio_observability_report.json').write_text(json.dumps(report,indent=2)+'\n'); print('VIO observability lab:',report['status']); return 0 if report['status']=='PASS' else 1
if __name__=='__main__': raise SystemExit(main())
